'use client';

import { useRef } from 'react';
import gsap from 'gsap';
import { useGSAP } from '@gsap/react';
import { useStateContext } from '@/hooks/State';
import { isLightTheme } from '@/utilities/utils';

type TPixelMask = {
  children: React.ReactNode;
};

const PixelMask = ({ children }: TPixelMask): React.ReactNode => {
  // Hooks
  const mask = useRef(null);
  const { theme } = useStateContext();

  gsap.registerPlugin(useGSAP);

  useGSAP(
    () => {
      handleMask();
    },
    { scope: mask },
  );

  // Handlers
  /**
   * @description Mask animation handler
   * @author Luca Cattide
   * @date 16/07/2025
   */
  const handleMask = (): void => {
    gsap.to('.pixel-mask__pixel', {
      duration: 0.1,
      opacity: 0,
      stagger: { amount: 1, from: 'random' },
    });
  };

  return (
    // Mask Start
    <div className="pixel-mask__container relative overflow-hidden">
      {isLightTheme(theme) ? (
        <svg
          className="pixel-mask absolute"
          viewBox="0 0 4896 4311"
          preserveAspectRatio="xMinYMin meet"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          ref={mask}
        >
          <rect
            className="pixel-mask__pixel"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="479"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="958"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="1437"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="1916"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="2395"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="2874"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="3353"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="3832"
            width="612"
            height="479"
            fill="#3E32A2"
            stroke="#3E32A2"
            strokeWidth="6"
          />
        </svg>
      ) : (
        <svg
          className="pixel-mask absolute"
          viewBox="0 0 4896 4311"
          preserveAspectRatio="xMinYMin meet"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          ref={mask}
        >
          <rect
            className="pixel-mask__pixel"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="612"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1224"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="1836"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="2448"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3060"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="3672"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="479"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="958"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="1437"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="1916"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="2395"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="2874"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="3353"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
          <rect
            className="pixel-mask__pixel"
            x="4284"
            y="3832"
            width="612"
            height="479"
            fill="#000"
            stroke="#000"
            strokeWidth="6"
          />
        </svg>
      )}
      {children}
    </div>
    // Mask End
  );
};

export default PixelMask;
