name: LC 2.0 CD
run-name: LC 2.0 Content-Delivery
on:
  # Pipeline dependency
  workflow_run:
    workflows: [LC 2.0 CI]
    types: [completed]
    branches: [main]
env:
  # Vercel
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  # Repository - TODO: Abstract to pass via `vars`
  DEPENDENCIES_PATH: |
    ~/.cache
    ./node_modules
  DEPENDENCIES_KEY: '**/package-lock.json'
  ARTIFACTS_NAME: lc-2.0-production
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_TOKEN_LC }}
    # Pipeline Check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Getting dependencies & production artifacts
        uses: ./.github/actions/dependencies
        with:
          dependencies-path: ${{ env.DEPENDENCIES_PATH }}
          dependencies-key: ${{ env.DEPENDENCIES_KEY }}
          artifacts-name: ${{ env.ARTIFACTS_NAME }}
          external: true
      - name: Getting production dependencies
        uses: ./.github/actions/dependencies
        with:
          dependencies-path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          dependencies-key: ${{ runner.os }}-nextjs-${{ hashFiles(env.DEPENDENCIES_KEY) }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          dependencies-key-restore: |
            ${{ runner.os }}-nextjs-${{ hashFiles(env.DEPENDENCIES_KEY) }}-
          production: true
      # Proceeding manually since official action got issues
      - name: Install Sanity CLI
        run: npm i -g sanity@latest
      - name: Deploy Backend
        run: npm run deploy
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Getting dependencies & production artifacts
        uses: ./.github/actions/dependencies
        with:
          dependencies-path: ${{ env.DEPENDENCIES_PATH }}
          dependencies-key: ${{ env.DEPENDENCIES_KEY }}
          artifacts-name: ${{ env.ARTIFACTS_NAME }}
          external: true
      - name: Getting production dependencies
        uses: ./.github/actions/dependencies
        with:
          dependencies-path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          dependencies-key: ${{ runner.os }}-nextjs-${{ hashFiles(env.DEPENDENCIES_KEY) }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          dependencies-key-restore: |
            ${{ runner.os }}-nextjs-${{ hashFiles(env.DEPENDENCIES_KEY) }}-
          production: true
      - name: Install Vercel CLI
        run: npm i --g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_LC }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_LC }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_LC }}
  failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
