name: LC 2.0 CD
run-name: LC 2.0 Continuous-Delivery
on:
  # Pipeline dependency
  workflow_run:
    workflows: [LC 2.0 CI]
    types: [completed]
    branches: [main]
env:
  # Vercel
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  # Repository
  DEPENDENCIES_PATH: |
    ~/.cache
    ./node_modules
  DEPENDENCIES_KEY: '**/package-lock.json'
jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_TOKEN_LC }}
    # Pipeline Check
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      # Get dependencies
      - name: Getting dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
      # Get production dependencies
      - name: Getting production dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      # Download stored production version
      - name: Getting production artifacts
        uses: actions/download-artifact@v4
        with:
          name: lc-2.0-production
          github-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      # Proceeding manually since official action got issues
      - name: Install Sanity CLI
        run: npm i -g sanity@latest
      - name: Deploy Backend
        run: npm run deploy
  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      id-token: write
    needs: deploy-backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Getting dependencies
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.DEPENDENCIES_PATH }}
          key: modules-${{ hashFiles(env.DEPENDENCIES_KEY) }}
      - name: Getting production dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      - name: Getting production artifacts
        uses: actions/download-artifact@v4
        with:
          name: lc-2.0-production
          github-token: ${{ secrets.GH_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Install Vercel CLI
        run: npm i --g vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN_LC }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN_LC }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN_LC }}
  failure:
    runs-on: ubuntu-latest
    permissions: {}
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
