name: LC 2.0 CI
run-name: LC 2.0 Content-Integration
on:
  push:
    branches: [main]
  # For collaborations
  pull_request:
    branches: [main]
env:
  # Frontend
  FRONTEND_URL: ${{ vars.FRONTEND_URL }}
  # Backend
  NEXT_PUBLIC_API_VERSION: ${{ vars.NEXT_PUBLIC_API_VERSION }}
  NEXT_PUBLIC_DATASET: ${{ vars.NEXT_PUBLIC_DATASET }}
  NEXT_PUBLIC_PROJECT_ID: ${{ secrets.NEXT_PUBLIC_PROJECT_ID }}
  # Analytics
  NEXT_PUBLIC_ANALYTICS_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_ID }}
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'
      - name: Create `env` file and provide environment variables
        run: |
          touch .env
          echo FRONTEND_URL=$BASE_URL >> .env
          echo NEXT_PUBLIC_API_VERSION=$NEXT_PUBLIC_API_VERSION >> .env
          echo NEXT_PUBLIC_PROJECT_ID=$NEXT_PUBLIC_PROJECT_ID >> .env
          echo NEXT_PUBLIC_DATASET=$NEXT_PUBLIC_DATASET >> .env
          echo NEXT_PUBLIC_ANALYTICS_ID=$NEXT_PUBLIC_ANALYTICS_ID >> .env
          mv .env frontend/
      - name: Installing dependencies
        run: npm run setup:ci
      # Cache dependencies for future reuse
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      # Store project for future reuse
      - name: Archive project artifacts
        uses: actions/upload-artifact@v4
        with:
          name: lc-2.0
          include-hidden-files: true
          # Exclude dependencies to lighten artifacts (provided via cache)
          path: |
            .
            !./node_modules
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      # Get dependencies
      - name: Getting dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache
            ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      # Download stored project
      - name: Getting project artifacts
        uses: actions/download-artifact@v4
        with:
          name: lc-2.0
      - name: Test applications - Unit/Integration
        run: npm run test
      - name: Test applications - E2E
        uses: cypress-io/github-action@v6
        with:
          project: ./frontend
          build: npm run build -w frontend
          start: npm run start -w frontend
      # Tests report storing for QA/checks
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: lc-2.0-test
          path: ./**/coverage/**/*
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      # Get dependencies
      - name: Getting dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      # Download stored project
      - name: Getting project artifacts
        uses: actions/download-artifact@v4
        with:
          name: lc-2.0
      - name: Build packages
        run: npm run build
      # Cache production dependencies for future reuse
      - name: Cache production dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ${{ github.workspace }}/.next/cache
          # Generate a new cache whenever packages or source files change.
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          # If source files changed but packages didn't, rebuild from a prior cache.
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
      # Store production versions for future reuse
      - name: Archive production verions
        uses: actions/upload-artifact@v4
        with:
          name: lc-2.0-production
